baseURL = "/"
languageCode = "fr-FR"
title = "Bahia Display - Agence de communication"
disableKinds = ["taxonomyTerm"]
googleAnalytics = "UA-122248157-1"

[params]
  title = "Bahia Display"
  description = "Agence de communication, spécialisée dans l'impression numerique"

[menu]
  [[menu.main]]
    name = "Accueil"
    identifier = "home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Présentation"
    identifier = "presentation"
    url = "/#presentation"
    weight = 20

  [[menu.main]]
    name = "Services"
    identifier = "services"
    url = "/services/"
    weight = 30

  [[menu.main]]
    name = "Références"
    identifier = "refs"
    url = "/references"
    weight = 40

  [[menu.main]]
    name = "Contact"
    identifier = "contact"
    url = "#contact"
    weight = 50
