display_url: "https://grp-platinum.netlify.com"

backend:
  name: git-gateway

media_folder: "content/media"
public_folder: "media"

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "content/_index.md"
        label: "Page d'accueil"
        name: "home"
        fields:
          - label: "Slider"
            name: carousel
            widget: list
            fields:
              - { label: "Image", name: image, widget: image }
              - { label: "Texte (optionnel)", name: caption, widget: string }
          - { label: "Image Principale", name: "intro_image", widget: "image" }
          - { label: "Presentation", name: "presentation", widget: "text" }

      - file: "content/references/_index.md"
        label: "Références"
        name: "references"
        editor:
          preview: false
        fields:
          - {label: "Titre", name: "heading", widget: "string", required: true}
          - {label: "En-tete", name: "body", widget: "text", required: true}
          - label: Références
            name: refs
            singular_label: Référence
            widget: list
            fields:
              - { label: "Logo", name: image, widget: image }
              - { label: "Afficher", name: publish, widget: boolean }

      - file: "content/references/_index.md"
        label: "Services"
        name: "services"
        editor:
          preview: false
        fields:
          - {label: "Titre", name: "heading", widget: "string", required: true}
          - {label: "En-tete", name: "body", widget: "text", required: true}
          - label: Services
            name: services
            singular_label: Service
            widget: list
            fields:
              - { label: "Titre", name: "title", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Image", name: "image", widget: "image" }

      - file: "content/contact/_index.md"
        label: "Contact"
        name: "Contact"
        editor:
          preview: false
        fields:
          - { label: "En-tete", name: "body", widget: "text", required: true }
          - { label: "Téléphone Principal", name: "principal_phone", widget: "string", required: true }
          - { label: "Téléphone N°2", name: "phone_2", widget: "string" }
          - { label: "Téléphone N°3", name: "phone_3", widget: "string" }
          - { label: "Adresse N°1", name: "address_1", widget: "string" }
          - { label: "Adresse N°2", name: "address_2", widget: "string" }
          - { label: "Adresse N°3", name: "address_3", widget: "string" }
          - { label: "E-mail N°1", name: "email_1", widget: "string" }
          - { label: "E-mail N°2", name: "email_2", widget: "string" }
          - { label: "E-mail N°3", name: "email_3", widget: "string" }
          - { label: URL page Facebook, name: facebook, widget: string }
          - { label: URL profile LinkedIn, name: linkedin, widget: string }
          - { label: URL Twitter, name: twitter, widget: string }
