display_url: "https://grp-platinum.netlify.com"

backend:
  name: git-gateway

media_folder: "content/media"
public_folder: "media"

collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - file: "content/_index.md"
        label: "Page d'accueil"
        name: "home"
        fields:
          - label: "Slider"
            name: carousel
            widget: list
            fields:
              - { label: "Image", name: image, widget: image }
              - { label: "Texte (optionnel)", name: caption, widget: string }

          - label: Services
            name: services
            widget: list
            fields:
              - { label: Nom du service, name: name, widget: string }
              - { label: Image, name: image, widget: image, required: true }

      - file: "content/presentation/_index.md"
        label: "Présentation"
        name: "presentation"
        fields:
          - label: "Introduction (Visible sur la page d'accueil)"
            name: intro
            widget: object
            fields:
              - { label: "Text d'introduction", name: text, widget: text }
              - { label: Image, name: image, widget: image }
          - { label: "Texte (Visible sur la page de présentation)", name: body, widget: markdown }

      - file: "content/moyens/_index.md"
        label: "Nos moyens"
        name: "means"
        fields:
          - { label: "Texte en-tête", name: text, widget: text }
          - { label: "Couverture en-tête", name: header_image, widget: image }

          - label: Outils
            name: tools
            widget: object
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Entrées, name: items, widget: markdown }

          - label: Matériels roulants
            name: vehicles
            widget: object
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Entrées, name: items, widget: markdown }

          - label: Engins
            name: machines
            widget: object
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Entrées, name: items, widget: markdown }

      - file: "content/references/_index.md"
        label: "Références"
        name: "references"
        editor:
          preview: false
        fields:
          - {label: "Titre", name: "heading", widget: "string", required: true}
          - {label: "En-tete", name: "body", widget: "text", required: true}
          - label: Références
            name: refs
            singular_label: Référence
            widget: list
            fields:
              - { label: "Logo", name: image, widget: image }
              - { label: "Afficher", name: publish, widget: boolean }

      - file: "content/contact/_index.md"
        label: "Contact"
        name: "Contact"
        editor:
          preview: false
        fields:
          - { label: "En-tete", name: "body", widget: "text", required: true }
          - { label: "Téléphone Principal", name: "principal_phone", widget: "string", required: true }
          - { label: "Téléphone N°2", name: "phone_2", widget: "string" }
          - { label: "Téléphone N°3", name: "phone_3", widget: "string" }
          - { label: "Adresse N°1", name: "address_1", widget: "string" }
          - { label: "Adresse N°2", name: "address_2", widget: "string" }
          - { label: "Adresse N°3", name: "address_3", widget: "string" }
          - { label: "E-mail N°1", name: "email_1", widget: "string" }
          - { label: "E-mail N°2", name: "email_2", widget: "string" }
          - { label: "E-mail N°3", name: "email_3", widget: "string" }
          - { label: URL page Facebook, name: facebook, widget: string }
          - { label: URL profile LinkedIn, name: linkedin, widget: string }
          - { label: URL Twitter, name: twitter, widget: string }